name: Hamekoz

on:
  pull_request:
    branches: [$default-branch]
  push:
    branches: [$default-branch, "INT"]
    tags:
      - v*.*.*

jobs:
  conventional-commits:
    name: Conventional Commits
    uses: hamekoz/.github/.github/workflows/conventional-commits.yml@main
  continuous-integration:
    name: Continuous Integration
    needs: conventional-commits
    uses: hamekoz/.github/.github/workflows/dotnet.yml@main
  continuous-delivery:
    if: ${{ github.event_name == 'push' }}
    name: Continuous Delivery
    needs: [conventional-commits, continuous-integration]
    uses: hamekoz/.github/.github/workflows/continuous-delivery-nuget.yml@main
    secrets: inherit
  docker:
    if: ${{ github.event_name == 'push' }}
    name: Continuous Delivery Default Project
    uses: Hamekoz/.github/.github/workflows/continuous-delivery-dockerfile.yml@main
    secrets: inherit
    with:
      dockerfile-path: "DefaultProject/Dockerfile"
      docker-image-name: "hamekoz-docker-image-name-default-example"
  docker-another:
    if: ${{ github.event_name == 'push' }}
    name: Continuous Delivery Another Project
    uses: Hamekoz/.github/.github/workflows/continuous-delivery-dockerfile.yml@main
    secrets: inherit
    with:
      dockerfile-path: "AnotherProject/Dockerfile"
      docker-image-name: "hamekoz-docker-image-name-another-example"
