name: Continuous Delivery

on:
  workflow_call:
    inputs:
      runner:
        description: "El runner donde se ejecutará el trabajo (ej. ubuntu-latest o self-hosted)"
        required: false
        default: "ubuntu-latest"
        type: string
      publish-nuget-org:
        description: "Publicar también en NuGet.org (default: true)"
        required: false
        default: true
        type: boolean
      nuget-version:
        description: "Versión del NuGet a publicar (default: auto-detect con GitVersion)"
        required: false
        default: ""
        type: string

jobs:
  publish-to-github-packages:
    name: Publish NuGet to GitHub Packages
    uses: ./.github/workflows/publish-nuget-to-github-packages.yml
    with:
      runner: ${{ inputs.runner }}
      nuget-version: ${{ inputs.nuget-version }}
    secrets: inherit

  publish-to-nuget-org:
    name: Publish NuGet to NuGet.org
    if: ${{ inputs.publish-nuget-org }}
    uses: ./.github/workflows/publish-nuget-to-nuget-org.yml
    with:
      runner: ${{ inputs.runner }}
      nuget-version: ${{ inputs.nuget-version }}
    secrets: inherit
