name: Continuous Delivery

on:
  workflow_call:
    inputs:
      runner:
        description: "El runner donde se ejecutará el trabajo (ej. ubuntu-latest o self-hosted)"
        required: false
        default: "ubuntu-latest"
        type: string
      dockerfile-path:
        description: "Path to Dockerfile to use for build image"
        default: "Dockerfile"
        type: string
      docker-image-name:
        description: "The name of the docker image to delivery"
        required: true
        type: string

jobs:
  publish-to-github-packages:
    name: Publish Docker Image to GitHub Packages
    uses: ./.github/workflows/publish-docker-image-to-github-packages.yml
    with:
      runner: ${{ inputs.runner }}
      dockerfile-path: ${{ inputs.dockerfile-path }}
      docker-image-name: ${{ inputs.docker-image-name }}
    secrets: inherit

  publish-to-dockerhub:
    name: Publish Docker Image to Docker Hub
    uses: ./.github/workflows/publish-docker-image-to-dockerhub.yml
    with:
      runner: ${{ inputs.runner }}
      dockerfile-path: ${{ inputs.dockerfile-path }}
      docker-image-name: ${{ inputs.docker-image-name }}
    secrets: inherit
