name: Conventions

on:
  workflow_call:

jobs:
  conventional-commits:
    name: Conventional Commits
    uses: hamekoz/.github/.github/workflows/conventional-commits.yml@main
  code-format:
    name: Code Format
    uses: hamekoz/.github/.github/workflows/code-format-verification.yml@main
