name: Conventional Commits

on:
  workflow_call:
    inputs:
      runner:
        description: "El runner donde se ejecutará el trabajo (ej. ubuntu-latest o self-hosted)"
        required: false
        default: "ubuntu-latest"
        type: string

jobs:
  conventional-commits:
    name: Conventional Commits
    runs-on: ${{ inputs.runner }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
#      - name: Ejecutar Gitlint
#        uses: aschbacd/gitlint-action@v1.2.0

      - name: Install gitlint
        shell: bash
        run: |
          python3 -m pip install gitlint
      - name: Run gitlint
        shell: bash
        run: |
          # Lint everything from the base to the latest
          gitlint --commits "${{ github.event.pull_request.base.sha }}..HEAD" \
            -c general.contrib=contrib-title-conventional-commits \
            -c general.ignore=body-is-missing,body-max-line-length \
            -c title-max-length.line-length=100
