name: Hamekoz

on:
  push:
    branches: [main, master, develop]
  pull_request:
    branches: [main, master, develop]

jobs:
  conventional-commits:
    name: Conventions
    uses: hamekoz/.github/.github/workflows/conventions.yml@main
